require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CubiCasa/podspecs.git'

target 'ReactNativeCubiCasaSdk' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'ZIPFoundation', '~> 0.9'
  pod 'CubiCapture'

  post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
end
